"""Add jumlah field and change tipe_barang

Revision ID: 11c3e499a49a
Revises: 8f9033f4f348
Create Date: 2024-10-24 10:12:48.163669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11c3e499a49a'
down_revision = '8f9033f4f348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah', sa.Integer(), nullable=False))
        batch_op.alter_column('tipe_barang',
               existing_type=mysql.ENUM('barang_jual', 'spare_part', 'barang_sewa'),
               type_=sa.JSON(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_list', schema=None) as batch_op:
        batch_op.alter_column('tipe_barang',
               existing_type=sa.JSON(),
               type_=mysql.ENUM('barang_jual', 'spare_part', 'barang_sewa'),
               nullable=False)
        batch_op.drop_column('jumlah')

    # ### end Alembic commands ###
