"""added nama_pembeli column to the database

Revision ID: 3c5490c5624a
Revises: 12b8932f58e5
Create Date: 2024-12-19 12:19:12.325241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5490c5624a'
down_revision = '12b8932f58e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_pembeli', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_list', schema=None) as batch_op:
        batch_op.drop_column('nama_pembeli')

    # ### end Alembic commands ###
