"""Add source_type column to ItemList

Revision ID: 9796e7470c11
Revises: 7896e504df41
Create Date: 2024-11-08 14:50:50.567122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9796e7470c11'
down_revision = '7896e504df41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_list', schema=None) as batch_op:
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
