"""Remove unique constraint from nomor_seri

Revision ID: c76755304729
Revises: 9796e7470c11
Create Date: 2024-11-22 14:33:32.842352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76755304729'
down_revision = '9796e7470c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_list', schema=None) as batch_op:
        batch_op.drop_index('nomor_seri')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_list', schema=None) as batch_op:
        batch_op.create_index('nomor_seri', ['nomor_seri'], unique=True)

    # ### end Alembic commands ###
